begin;
select plan(26);
select has_function('public', 'create_payfast_payment_attempt', array['text','text','uuid','text','boolean','boolean']);
select has_function('public', 'process_payfast_itn', array['text','text','integer','text']);
select has_function('public', 'finalise_paid_booking_calendar', array['uuid','boolean','text','text']);
select has_function('public', 'mark_payment_refund_state', array['uuid','payment_state']);
select has_function('public', 'can_mutate_finance', array[]::text[]);
select has_index('public', 'payments', 'payments_one_open_payfast_attempt_per_booking');
select has_index('public', 'payment_events', 'payment_events_provider_event_global_unique');
select has_trigger('public', 'payments', 'payments_snapshot_immutable');
select has_trigger('public', 'payment_events', 'payment_events_immutable');
select function_privs_are('public', 'create_payfast_payment_attempt', array['text','text','uuid','text','boolean','boolean'], 'service_role', array['EXECUTE']);
select function_privs_are('public', 'process_payfast_itn', array['text','text','integer','text'], 'service_role', array['EXECUTE']);
select function_privs_are('public', 'finalise_paid_booking_calendar', array['uuid','boolean','text','text'], 'service_role', array['EXECUTE']);
select function_privs_are('public', 'mark_payment_refund_state', array['uuid','payment_state'], 'authenticated', array['EXECUTE']);
select isnt_empty($$select 1 from pg_proc where proname='create_payfast_payment_attempt' and prosrc like '%price_cents%'$$, 'payment snapshots the booking amount');
select isnt_empty($$select 1 from pg_proc where proname='process_payfast_itn' and prosrc like '%for update%'$$, 'ITN locks the payment');
select isnt_empty($$select 1 from pg_proc where proname='process_payfast_itn' and prosrc like '%CALENDAR_SYNC_PENDING%'$$, 'paid booking queues calendar sync');
select isnt_empty($$select 1 from pg_proc where proname='finalise_paid_booking_calendar' and prosrc like '%notification_outbox%'$$, 'confirmation outbox is transactional');
select isnt_empty($$select 1 from pg_proc where proname='can_mutate_finance' and prosrc like '%current_session_is_aal2%'$$, 'owner finance mutation requires aal2');
select isnt_empty($$select 1 from pg_proc where proname='mark_payment_refund_state' and prosrc like '%REFUND_PENDING%'$$, 'refund transitions are constrained');
select isnt_empty($$select 1 from pg_proc where proname='create_payfast_payment_attempt' and prosrc like '%price_cents < 500%'$$, 'PayFast minimum is enforced from snapshot');
select isnt_empty($$select 1 from pg_proc where proname='process_payfast_itn' and prosrc like '%payment.received_after_release%'$$, 'late valid payment becomes manual reconciliation');
select isnt_empty($$select 1 from pg_proc where proname='release_booking_hold' and prosrc like $needle$state = 'HELD'$needle$ and prosrc not like '%PAYMENT_PENDING%', 'public release is held-only');
select isnt_empty($$select 1 from pg_proc where proname='create_payfast_payment_attempt' and prosrc like '%PAYMENT_EARLY_PERFORMANCE_ACCEPTANCE_REQUIRED%'$$, 'early performance acceptance is server-enforced');
select isnt_empty($$select 1 from pg_proc where proname='create_payfast_payment_attempt' and prosrc like '%legal_version%'$$, 'legal version is snapshotted in immutable event');
select policies_are('public', 'payments', array['payments_staff_read']);
select policies_are('public', 'payment_events', array['payment_events_staff_read']);
select * from finish();
rollback;
