import { addConsentVersionAction } from "@/app/admin/schedule-actions";
import { adminFormat, requireScheduleAccess } from "@/lib/booking/admin";

export default async function ConsentsPage() {
  const { supabase, editable } = await requireScheduleAccess(["owner", "scheduler", "auditor"]);
  const { data, error } = await supabase.from("consent_versions").select("*").eq("purpose", "booking").order("effective_at", { ascending: false });
  if (error) throw new Error("SCHEDULE_CONSENTS_LOAD_FAILED");
  return <div className="admin-content"><div className="admin-page-heading"><div><p className="eyebrow">Versioned wording</p><h1>Booking consent</h1><p>Public booking fails closed unless one current booking consent version is active.</p></div></div>{editable ? <section className="admin-panel"><h2>Add a consent version</h2><form action={addConsentVersionAction} className="admin-form"><label className="admin-field">Version<input maxLength={30} name="version" required /></label><label className="admin-field">Approved wording<textarea name="wording" required rows={5} /></label><label className="admin-field">Effective from, SAST<input name="effectiveAt" required type="datetime-local" /></label><label className="admin-check"><input name="active" type="checkbox" /> Activate this version and retire the previous active version</label><button className="admin-button admin-button-primary" type="submit">Save consent version</button></form></section> : null}<section className="admin-panel"><h2>Consent history</h2>{data?.length ? <div className="admin-card-list">{data.map((consent) => <article key={consent.id}><div><span className={`admin-status admin-status-${consent.active ? "published" : "archived"}`}>{consent.active ? "Active" : "Retired"}</span><h3>Version {consent.version}</h3><p>{consent.wording}</p></div><small>Effective {adminFormat(consent.effective_at)}</small></article>)}</div> : <div className="admin-empty"><strong>No approved consent wording</strong><p>Public booking is safely unavailable.</p></div>}</section></div>;
}
