import { saveServiceAction } from "@/app/admin/schedule-actions";
import { requireScheduleAccess } from "@/lib/booking/admin";
import { formatZar } from "@/lib/booking/time";

export default async function ServicesPage() {
  const { supabase, editable } = await requireScheduleAccess(["owner", "scheduler", "auditor"]);
  const { data } = await supabase.from("services").select("*").order("position");
  return <div className="admin-content"><div className="admin-page-heading"><div><p className="eyebrow">Johannesburg scheduler</p><h1>Services</h1><p>Duration, buffer and ZAR price are trusted from the database at booking time.</p></div></div>{editable ? <section className="admin-panel"><h2>Add a service</h2><form action={saveServiceAction} className="admin-form admin-form-grid"><label className="admin-field">Name<input name="name" required /></label><label className="admin-field">Slug<input name="slug" required /></label><label className="admin-field admin-field-wide">Description<textarea name="description" required /></label><label className="admin-field">Duration, minutes<input min="15" name="durationMinutes" required type="number" /></label><label className="admin-field">Buffer, minutes<input defaultValue="0" min="0" name="bufferMinutes" required type="number" /></label><label className="admin-field">Price, rand<input min="0" name="priceRands" required step="0.01" type="number" /></label><label className="admin-field">Position<input defaultValue="0" min="0" name="position" required type="number" /></label><label className="admin-check"><input name="active" type="checkbox" /> Accept bookings</label><button className="admin-button admin-button-primary" type="submit">Save service</button></form></section> : null}<section className="admin-panel"><h2>Configured services</h2>{data?.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Service</th><th>Timing</th><th>Price</th><th>Status</th></tr></thead><tbody>{data.map((service) => <tr key={service.id}><td><strong>{service.name}</strong><br/><small>{service.slug}</small></td><td>{service.duration_minutes} min + {service.buffer_minutes} min buffer</td><td>{formatZar(service.price_cents)}</td><td><span className={`admin-status admin-status-${service.active ? "published" : "archived"}`}>{service.active ? "Active" : "Paused"}</span></td></tr>)}</tbody></table></div> : <div className="admin-empty"><strong>No services yet</strong><p>Public booking remains safely unavailable.</p></div>}</section></div>;
}
