import Link from "next/link";

import { adminFormat } from "@/lib/booking/admin";
import { formatZar } from "@/lib/booking/time";
import { requireFinanceAccess } from "@/lib/payment/admin";

export default async function PaymentsPage({ searchParams }: { searchParams: Promise<{reconciliation?:string}> }) {
  const filterReconciliation = (await searchParams).reconciliation === "required";
  const { supabase } = await requireFinanceAccess();
  let paymentsQuery = supabase.from("payments").select("id,provider,provider_reference,amount_cents,currency,state,reconciliation_required,reconciliation_reason,reconciled_at,created_at,paid_at,bookings(public_reference,state)").order("created_at", { ascending: false }).limit(200);
  if (filterReconciliation) paymentsQuery = paymentsQuery.eq("reconciliation_required", true);
  const [paymentsResult, receiptsResult, reconciliationResult] = await Promise.all([
    paymentsQuery,
    supabase.from("webhook_receipts").select("id,provider_event_id,payload_hash,signature_valid,processed_at,processing_error,received_at").eq("provider", "payfast").order("received_at", { ascending: false }).limit(50),
    supabase.from("payments").select("id", { count: "exact", head: true }).eq("reconciliation_required", true),
  ]);
  if (paymentsResult.error || receiptsResult.error || reconciliationResult.error) throw new Error("PAYMENTS_LOAD_FAILED");
  const payments = paymentsResult.data;
  const receipts = receiptsResult.data;
  return <div className="admin-content"><div className="admin-page-heading"><div><p className="eyebrow">Finance</p><h1>Payments</h1><p>Provider states and operational reconciliation, without card data or booking health information.</p></div></div>{reconciliationResult.count ? <section className="admin-panel payment-admin-alert"><h2>{reconciliationResult.count} payment{reconciliationResult.count === 1 ? "" : "s"} require reconciliation</h2><p>Payment was received after the booking had expired or been cancelled. Do not ask the client to pay again. Review the appointment and refund path.</p><Link className="admin-button admin-button-primary" href="/admin/finance/payments?reconciliation=required">Show reconciliation queue</Link></section> : null}<section className="admin-panel"><div className="admin-panel-heading"><div><h2>{filterReconciliation ? "Reconciliation queue" : "Payment attempts"}</h2></div>{filterReconciliation ? <Link href="/admin/finance/payments">Show all payments</Link> : null}</div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Booking</th><th>Booking state</th><th>Amount</th><th>Payment state</th><th>Created</th><th /></tr></thead><tbody>{payments?.map((payment) => { const booking = payment.bookings as unknown as {public_reference:string;state:string}; return <tr key={payment.id}><td>{booking.public_reference}{payment.reconciliation_required ? <strong className="admin-reconciliation-flag">Action required</strong> : null}</td><td>{booking.state.replaceAll("_", " ")}</td><td>{formatZar(payment.amount_cents)}</td><td><span className="admin-status admin-status-neutral">{payment.state.replaceAll("_", " ")}</span></td><td>{adminFormat(payment.created_at)}</td><td><Link href={`/admin/finance/payments/${payment.id}`}>Review</Link></td></tr>; })}</tbody></table></div>{!payments?.length ? <div className="admin-empty"><strong>{filterReconciliation ? "No unresolved reconciliation cases" : "No payment attempts"}</strong></div> : null}</section><section className="admin-panel"><h2>Recent PayFast webhook receipts</h2><p className="admin-security-note">Only a payload hash, validation outcome and operational error code are retained. Raw form data and card information are never shown.</p>{receipts?.length ? <ul className="admin-activity-list">{receipts.map((receipt) => <li key={receipt.id}><span className="admin-status admin-status-neutral">{receipt.signature_valid ? receipt.processed_at ? "processed" : "validated" : "rejected"}</span><strong>Hash {receipt.payload_hash.slice(0, 12)}… {receipt.processing_error ? `· ${receipt.processing_error}` : ""}</strong><time>{adminFormat(receipt.received_at)}</time></li>)}</ul> : <div className="admin-empty"><strong>No webhook receipts</strong><p>Browser return pages do not create payment receipts.</p></div>}</section></div>;
}
