import { createBookingCalendarAdapter } from "@/lib/booking/calendar-factory";
import { adminFormat, requireScheduleAccess } from "@/lib/booking/admin";

export default async function CalendarHealthPage() {
  const { supabase } = await requireScheduleAccess(["owner", "scheduler", "auditor"]);
  let adapterName = "unavailable"; let health = { available: false, message: "Calendar configuration needs attention." };
  try { const adapter = createBookingCalendarAdapter(); adapterName = adapter.name; health = await adapter.health(); } catch { /* fail closed */ }
  const { data } = await supabase.from("calendar_sync_events").select("id,direction,outcome,occurred_at").order("occurred_at", { ascending: false }).limit(50);
  return <div className="admin-content"><div className="admin-page-heading"><div><p className="eyebrow">External integration</p><h1>Calendar health</h1><p>Google Calendar is checked for busy periods. Postgres remains the booking source of truth.</p></div><span className={`admin-status admin-status-${health.available ? "published" : "archived"}`}>{health.available ? "Available" : "Fail closed"}</span></div><section className="admin-panel"><h2>{adapterName === "google" ? "Google Calendar" : adapterName === "mock" ? "Test calendar" : "Calendar unavailable"}</h2><p>{health.message}</p>{adapterName === "mock" ? <p className="admin-error">The deterministic mock is for tests and local development only. Production rejects it.</p> : null}<p>No booking is marked confirmed when a calendar operation fails.</p></section><section className="admin-panel"><h2>Recent reconciliation</h2>{data?.length ? <ul className="admin-activity-list">{data.map((item) => <li key={item.id}><span className="admin-status admin-status-neutral">{item.outcome}</span><strong>{item.direction}</strong><time>{adminFormat(item.occurred_at)}</time></li>)}</ul> : <div className="admin-empty"><strong>No reconciliation events</strong><p>Calendar event creation starts only after the paid confirmation transition in Task 5.</p></div>}</section></div>;
}
